### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Debuggernaut** [BloodDragon2580/CovenantMissionHelper#1]
Hey dude, this addon is great, but I'm wondering what your license is for it

After we all got burned by the prick behind Venture Plan, I'm kinda worried

Keep up the good work!

**Comment by BloodDragon2580** [comment]
I do not distribute the addon or anything like that. I don't make it public either. This is just for me. Should I get any message, I will set the repo to private.

**Comment by Debuggernaut** [comment]
ohh, sorry buddy, I mixed your repo up with the main one at https://github.com/Kreolix/CovenantMissionHelper

**Comment by BloodDragon2580** [comment]
No problem
